Repository wojiaotreaty/CSC207_Project, pull requests merged in 2023-12, with the labels that each got.

#31 Renaming of Add Project Related Files
  src/interface_adapter/add_project/AddProjectController.java
  src/interface_adapter/add_project/AddProjectPresenter.java
  src/use_case/add_project/AddProjectInputBoundary.java
  src/use_case/add_project/AddProjectInputData.java
  src/use_case/add_project/AddProjectInteractor.java
  src/use_case/add_project/AddProjectOutputBoundary.java
  src/use_case/add_project/AddProjectOutputData.java
Labels: bug, Syntax

#34 Dao tests corrected
  src/data_access/ProjectsDataAccessObject.java
  src/data_access/UsersDataAccessObject.java
  test/data_access/DataAccessObjectTestHelper.java
  test/data_access/ProjectsDataAccessObjectTest.java
  test/data_access/UsersDataAccessObjectTest.java
Labels: bug, Syntax, tests

#36 Entity Utility Methods Implementation
  src/entity/CommonProject.java
  src/entity/CommonTask.java
  src/entity/CommonUser.java
Labels: enhancement

#38 Add Project Use Case Interactor Unit Test Pull Request
  src/interface_adapter/dashboard/ProjectData.java
  src/use_case/add_project/AddProjectInteractor.java
  src/use_case/add_project/AddProjectOutputData.java
  test/use_case/add_project/AddProjectInteractionTest.java
  test/use_case/add_project/AddProjectInteractorUnitTest.java
Labels: enhancement, Syntax, tests

#39 Add Project Integration Test Pull Request
  test/use_case/add_project/AddProjectIntegrationTest.java
  test/use_case/add_project/AddProjectInteractionTest.java
Labels: tests

#41 Fixed apikey.txt Path and more Bug Fixes
  src/interface_adapter/dashboard/ProjectData.java
  src/use_case/add_project/AddProjectInteractor.java
  test/use_case/add_project/AddProjectInteractorUnitTest.java
Labels: bug

#42 Add Project Integration Test Typo Fix
  test/use_case/add_project/AddProjectIntegrationTest.java
Labels: bug

#43 Main implementation
  src/app/Main.java
  src/view/DashboardView.java
  src/view/LoginView.java
Labels: bug

#45 Signup integration test
  test/use_case/signup/SignupInteractorIntegrationTest.java
Labels: tests

#51 Set status use case implementation
  src/app/DashboardViewFactory.java
  src/app/Main.java
  src/data_access/UsersDataAccessObject.java
  src/entity/CommonProject.java
  src/entity/CommonUser.java
  src/entity/Project.java
  src/entity/User.java
  src/interface_adapter/set_status/SetStatusController.java
  src/interface_adapter/set_status/SetStatusPresenter.java
  src/use_case/set_status/SetStatusInputBoundary.java
  src/use_case/set_status/SetStatusInputData.java
  src/use_case/set_status/SetStatusInteractor.java
  src/use_case/set_status/SetStatusOutputBoundary.java
  src/use_case/set_status/SetStatusOutputData.java
  src/use_case/set_status/SetStatusUsersDataAccessInterface.java
  src/view/DashboardView.java
Labels: enhancement

#52 Send Notification api Call Change
  src/use_case/send_notification/NotificationInteractor.java
  src/view/DashboardView.java
Labels: enhancement

#53 Add Project Tests Fix
  test/use_case/add_project/AddProjectEndToEndTest.java
Labels: bug, tests

#56 Delete project tests
  .gitignore
  src/app/ProjectViewFactory.java
  src/data_access/ProjectsDataAccessObject.java
  src/data_access/UsersDataAccessObject.java
  src/interface_adapter/delete_project/DeleteProjectState.java
  src/use_case/delete_project/DeleteProjectInteractor.java
  src/view/DashboardView.java
  test/use_case/delete_project/DeleteProjectIntegrationTest.java
  test/use_case/delete_project/DeleteProjectInteractorUnitTest.java
  test/view/AddProjectEndToEndTest.java
  test/view/DeleteProjectEndToEndTest.java
Labels: enhancement, tests

#57 Added dall-e call to sendNotification use case.
  src/app/Main.java
  src/interface_adapter/dashboard/DashboardState.java
  src/interface_adapter/send_notification/NotificationPresenter.java
  src/use_case/send_notification/NotificationInteractor.java
  src/use_case/send_notification/NotificationOutputData.java
  src/view/DashboardView.java
Labels: enhancement

#62 Testing tests
  src/view/DashboardView.java
  test/use_case/add_project/AddProjectIntegrationTest.java
  test/use_case/send_notification/SendNotificationInteractorMessageUnitTest.java
  test/use_case/set_status/SetStatusInteractorUnitTest.java
  test/view/AddProjectEndToEndTest.java
  test/view/DeleteProjectEndToEndTest.java
  test/view/SendNotificationEndToEndTest.java
Labels: bug, tests

#61 Set status tests
  test/use_case/set_status/SetStatusIntegrationTest.java
  test/use_case/set_status/SetStatusInteractorUnitTest.java
  test/view/SetStatusEndToEndTest.java
Labels: tests

#63 made the integration test and the interactor unit test
  test/use_case/refactor_project/RefactorProjectIntegrationTest.java
  test/use_case/refactor_project/RefactorProjectInteractorUnitTest.java
Labels: tests

#60 Signup end to end test
  test/use_case/signup/SignupInteractorIntegrationTest.java
  test/view/SignupEndToEndTest.java
Labels: tests

#70 login end to end test
  src/view/LoginView.java
  test/view/LoginEndToEndTest.java
Labels: tests
